/*
    Even Fibonacci Numbers

    Each new term in the Fibonacci sequence is generated by adding the previous two
    terms. By starting with 1 and 2, the first 10 terms will be:

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed
    four million, find the sum of the even-valued terms.
*/
import { measureTime } from "../utils"

function solve(maxNum: number): number {
    let sum = 0  // Initialize sum to 0
    let a = 1
    let b = 2

    while (b < maxNum) {
        let temp = a + b
        a = b
        b = temp

        if (b % 2 === 0) {
            sum += b
        }
    }

    return sum
}


const [result, elapsedTime] = measureTime(() => solve(4000000))
console.log('result', result) // 4613732
console.log(`Elapsed Time: ${elapsedTime} milliseconds`)

export { }

